DROP TABLE IF EXISTS Student CASCADE,
DROP TABLE IF EXISTS Lecturer CASCADE,
DROP TABLE IF EXISTS Module CASCADE,
DROP TABLE IF EXISTS Marks CASCADE,
DROP TABLE IF EXISTS StudentContact CASCADE,
DROP TABLE IF EXISTS NextOfKinContact CASCADE,
DROP TABLE IF EXISTS Titles CASCADE,
DROP TABLE IF EXISTS Type CASCADE
